### ISSUE TITLE
Switch to ESLint

### ISSUE THREAD

**Issue by craigsimps** [craigsimps/gulp-wp-toolkit#2]
https://www.sitepoint.com/comparison-javascript-linting-tools/ summarises the difference between JSHint and ESLint, and a few other articles I've read also suggest it may be worth switching.

**Comment by GaryJones** [comment]
Instead of defining the basic eslint ourselves, let's try using https://github.com/ntwb/eslint-config-wordpress. I've started locally, but I'm getting the following error, and I'm not sure if this is due to what I've started or a general issue with `gulp lint:eslint`:

```
[14:48:22] Using gulpfile ...themes/gamajo/gulpfile.js
(node:28316) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[14:48:22] Starting 'lint:eslint'...
[14:48:22] 'lint:eslint' errored after 1.44 ms
[14:48:22] Error: Missing positive glob
    at Object.create (...themes/gamajo/node_modules/glob-stream/index.js:73:39)
    at Gulp.src (...themes/gamajo/node_modules/vinyl-fs/lib/src/index.js:33:23)
    at Gulp.module.exports (...themes/gamajo/node_modules/gulp-wp-toolkit/tasks/lint/eslint.js:21:10)
    at module.exports (...themes/gamajo/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (...themes/gamajo/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (...themes/gamajo/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (...themes/gamajo/node_modules/orchestrator/index.js:134:8)
    at ...themes/gamajo/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:609:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```
